# Generated by Django 3.0.7 on 2020-06-19 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_imagespost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagesPost',
        ),
    ]
